development:
  adapter: postgresql
  host: localhost
  database: jjones
  host: localhost

test: &test
  adapter: postgresql
  host: localhost
  database: jjones
  host: localhost
cucumber:
  <<: *test