development:
  adapter: postgresql
  host: localhost
  database: bethany_ruth_jones
  host: localhost

test: &test
  adapter: postgresql
  host: localhost
  database: bethany_ruth_jones
  host: localhost
cucumber:
  <<: *test